name: Publish release (main only)
on:
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        required: true
        description: 'Release type'
        default: 'patch'
        options:
          - patch
          - minor
          - major
      releaseBody:
        type: string
        required: true
        description: 'Release description'

jobs:
  publish:
    name: Publish to package registry
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Build and publish package
        uses: ./.github/actions/build-and-publish-package
        with:
          releaseType: ${{ github.event.inputs.releaseType }}
          id: version-bump

      - name: Create and push git tag
        if: steps.publish.outcome == 'success'
        run: |
          git tag ${{ steps.version-bump.outputs.version_tag }}
          git push origin ${{ steps.version-bump.outputs.version_tag }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version-bump.outputs.version_tag }}
          body: ${{ github.event.inputs.releaseBody }}
